##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  spring配置  ###################
spring:
  profiles:
    active: dev

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: D:/logs/rabbitmq-rpc-client.log

