##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  spring配置  ###################
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://123.207.66.156:3306/test?useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: ******

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/xncoding/pos/dao/repository/mapping/*.xml
  typeAliasesPackage: >
    com.xncoding.pos.dao.entity
  global-config:
    id-type: 0  # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性

logging:
  level:
    org.springframework.web.servlet: ERROR

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev
  cache:
    type: REDIS
  redis:
    host: 123.207.66.156
    port: 6379
    timeout: 0
    database: 0
    pool:
      max-active: 100
      max-wait: -1
      max-idle: 8
      min-idle: 0

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: E:/logs/app.log

