##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  项目启动端口  ###################
server.port: 8092

###################  spring配置  ###################
spring:
  profiles:
    active: dev

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: E:/logs/aop.log

